version: "3.8"

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - "$DB_PORT:5432"
    volumes:
      - data:/var/lib/postgresql/data

  admin:
    image: adminer
    ports:
      - "$ADMIN_PORT:8080"

volumes:
  data:
